name: Build Flet APK
on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install flet
          # Esto asegura que las herramientas de empaquetado estén listas
          pip install flet-pyinstaller 

      - name: Build APK
        # He quitado --product para evitar errores de metadatos y usado --verbose 
        # para que si falla, nos diga EXACTAMENTE por qué.
        run: flet build apk main.py --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
